### PR TITLE
Browserify

### PR DESCRIPTION
**Pull request by joshrowley**
Sets up browserify using [watchify](https://github.com/substack/watchify), allowing us to separate out our front end javascript into modules that can run inside Chromium.

Browserify doesn't know where to find module `ipc` since it's specific to the electron environment, however there is a neat workaround to it detailed in https://github.com/atom/electron/issues/1611#issuecomment-100044040.

### CODE REVIEW

**Comment by joshrowley** [comment]
@loganhasson This has https://github.com/flatiron-labs/environmentalizer_app/pull/1 in it, so might wanna review that first.

**Comment by loganhasson** [comment]
hallelujah. thanks @joshrowley, this is amazing! question...will I be able to just use jade by adding it as a dep and requiring as we do over on learn?

**Comment by joshrowley** [comment]
we can use jadeify, gonna set it up right now

**Comment by joshrowley** [comment]
:+1: jade set up

**Comment by loganhasson** [comment]
aaah, so nice. :+1:

**Pull request merged**
